name: 'AI Agent Context Optimizer'
description: 'Analyze your codebase and generate AI agent context documentation recommendations (CLAUDE.md, AGENTS.md, or similar) for any AI coding assistant'
author: 'guyaluk'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  claude-api-key:
    description: 'Claude API key for authentication'
    required: true
  context-file:
    description: 'AI agent context file to analyze (CLAUDE.md or AGENTS.md)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CLAUDE_API_KEY: ${{ inputs.claude-api-key }}
    CONTEXT_FILE: ${{ inputs.context-file }}